### ISSUE TITLE
Turn into a Wiki Bot

### ISSUE THREAD

**Issue by kushieda-minori** [kushieda-minori/vc_file_grouper#45]
# Need the following features

1. [x] Ability to take Wiki User credentials for API calls: #47
1. [x] Ability to (mass) upload images for a single card: #48
1. [ ] Ability to download page data for a single card and update different sections based on file data. Each section edit would be selectable (i.e. optional): #49 
    * Base into (Element, Rarity, Symbol, Evolution Accident info)
    * Stats
    * Exchange info (gold/medal)
    * Skills
    * Quotes
    * All info for missing evolution (i.e. Rebirth was added, add Stats & Skills & Quote)
    * Awakening and Rebirth information
    * upload only missing images (no overwrite)
    * Write the data back to the wiki
1. [ ] Ability to run through the card list and mass update a subset of information (see above): See #50
    * Allow "manual review" and "full automation". 
    * Full automation should generate report at the end of all changes made during the run.
    * Manual Review should have an option to switch to auto from the current starting point in the list.
    * The list of cards should be filterable (run off of the table filter?)

Initial implementation does not need to handle the "Amalgamation" section, can be done as a "phase 2"

# To get the raw page data use

https://valkyriecrusade.fandom.com/index.php?title=Oracle&action=raw

https://valkyriecrusade.fandom.com/index.php?title=Holy_Oracle_(new)&action=raw

https://valkyriecrusade.fandom.com/index.php?title=Card_Name&action=raw

# To save changes to a page use

https://valkyriecrusade.fandom.com/api.php

https://valkyriecrusade.fandom.com/api.php?action=help&modules=edit

# See Also

* https://community.fandom.com/wiki/Help:Bots
* https://en.wikipedia.org/wiki/Wikipedia:Creating_a_bot

**Comment by kushieda-minori** [comment]
Example edits from Adrian to keep into account:

![image](https://user-images.githubusercontent.com/14127109/101695936-50568780-3a43-11eb-99d9-6a81ce65bc6f.png)

![image](https://user-images.githubusercontent.com/14127109/101695973-5ea4a380-3a43-11eb-96ef-2224229fc135.png)

![image](https://user-images.githubusercontent.com/14127109/101695995-65331b00-3a43-11eb-954e-7ec325033643.png)

![image](https://user-images.githubusercontent.com/14127109/101696009-6cf2bf80-3a43-11eb-96a2-a907b2f7d459.png)
